remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: KiwiPebo's Gay Horror Blog
description: Comic reviews with a concentration of lgbtq+ and horror title